#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include "../lexicalAnalyzer.h"

// Functions
int main();
int lex();
void term();
void factor();
void expr();
int getToken();

// Classes
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

// Token Codes
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26

int main() {
    // Open the tokens file
    if ((in_fp = fopen("Parser/tokens.txt", "r")) == NULL) {
        printf("ERROR - cannot open tokens.txt \n");
        return 1;
    }
    
    // Get the first token
    if (!getToken()) {
        printf("ERROR - no tokens in input\n");
        fclose(in_fp);
        return 1;
    }
    
    expr(); // Start parsing

    fclose(in_fp);
    return 0;
}

int getToken() {
    if (fscanf(in_fp, "%d %99s", &nextToken, lexeme) == 2) {
        return 1;
    } else {
        return 0;
    }
}

void error() {
    printf("Error - invalid syntax\n");
    exit(1);
}

/*  expr
    Parses strings in the language generated by the rule:
    <expr> -> <term> {(+ | -) <term>}
    */
void expr() {
    printf("[expr\n");
/*  Parse the first term */
    term();
/*  As long as the next token is + or -, get
    the next token and parse the next term */
    while (nextToken == ADD_OP || nextToken == SUB_OP) {
        if (nextToken == ADD_OP) {
            printf(" [+]\n");
        } else {
            printf(" [-]\n");
        }
        lex();
        term();
    }
    
    printf("]\n");
}   /* End of function expr */

/*  term
    Parses strings in the language generated by the rule:
    <term> -> <factor> ((* | /) <factor>)
    */
void term() {
    printf("  [term\n");

/*  Parse the first factor */
    factor();

/*  As long as the next token is * or /, get the
    next token and parse the next factor */
    while (nextToken == MULT_OP || nextToken == DIV_OP) {
        if (nextToken == MULT_OP) {
            printf("  [*]\n");
        } else {
            printf("  [/]\n");
        }
        lex();
        factor();
    }
    
    printf("  ]\n");
}   /* End of function term */

/*  factor
    Parses strings in the language generated by the rule:
    <factor> -> id | int_constant | ( <expr> )
    */
void factor() {
    printf("    [factor\n");

/* Determine which RHS */
    if (nextToken == IDENT || nextToken == INT_LIT) {
        printf("   [id [%s]]\n", lexeme);
        lex();
    } else if (nextToken == LEFT_PAREN) {
        printf("   [(");
        lex();
        expr();
        if (nextToken == RIGHT_PAREN) {
            printf("   )]\n");
            lex();
        } else {
            error();
        }
    } else {
        error();
    }
    printf("  ]\n");
}